config/routes.rb
UmichStartups::Application.routes.draw do

  get "connections/create"
  get "connections/destroy"

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users do
    member do
      get :following, :followers, :memberships, :experiences, :skills
    end
  end
  resources :sessions
  resources :companies
  resources :connections
  resources :memberships
  resources :skills

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: :get
  match '/about', to: 'static_pages#about', via: :get
  match '/contact', to:'static_pages#contact', via: :get

  match '/signup', to: 'users#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/models/user.rb
class User < ActiveRecord::Base
  #deprecated in rails 4
  #attr_accessible :email, :name, :photo, :major, :password, :password_confirmation
  
  #connections
  has_many :connections, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :connections, source: :followed
  has_many :reverse_connections, foreign_key: "followed_id",
                                   class_name:  "Connection",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_connections, source: :follower
  
  #companies
  has_many :companies # TAKE THIS OUT
  has_many :memberships, dependent: :destroy # foreign_key: "user_id"

  #profile data
  has_many :skills
  has_many :experiences

  #profile photo
  #attr_accessor :photo
  #attr_accessor :photo_file_name
  has_attached_file :photo, :styles => { :medium => "200x200>", 
    :thumb => "100x100>", :tiny => "30X30>" }, 
    :default_url => "/assets/missing_:style.png"

  has_secure_password


  before_save { email.downcase! } #does this need { }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 } 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_UMICH_EMAIL = /\A[\w+\-.]+@umich.edu/i
  validates :email, presence: true, 
  					#format: { with: VALID_UMICH_EMAIL },
  					format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def following?(other_user)
    connections.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    connections.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    connections.find_by_followed_id(other_user.id).destroy
  end

  def member?(company)
    memberships.find_by(company_id: company.id)
  end

  def join_company!(company)
    memberships.create!(company_id: company.id)
  end

  def leave_company!(company)
    memberships.find_by(company_id: company.id).destroy
  end

  private
  	def create_remember_token
  		self.remember_token = SecureRandom.urlsafe_base64
  	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,
                  only: [:show, :index, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: [:destroy]              
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
	  	# flash[:success] = "Flash test"
  		redirect_to @user
  	else 
  		render 'new'
  	end
  end

  def show
    @user = User.find(params[:id])
    @memberships = @user.memberships
    @companies = []
    @memberships.each { |m| @companies.push Company.find(m.company_id) }
    @companies = @companies.paginate(page: params[:page], per_page: 1) 
  end

  def index
    #@users = User.all
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def edit
    @user = current_user
  end

  def update
    if @user.update_attributes(user_params)
        #Handle a successful update
        flash[:success] = "Profile updated"
        sign_in @user
        redirect_to @user
    else
        render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:success] = "#{user.name} has been deleted from the system"
    redirect_to users_url
  end

  def following
    @title = "Connections"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_connect'
  end

  def followers
    @title = "Connected Users"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_connect'
  end

  def memberships
    #find and display companies via memberships
    @user = User.find(params[:id])
    @memberships = @user.memberships.paginate(page: params[:page])
    @companies = []
    @memberships.each { |m| @companies.push Company.find(m.company_id) }
    @companies = @companies.paginate(page: params[:page])
    render 'show_companies'
  end

  def skills
    @new_skill = current_user.skills.build
    render 'add_skill'
  end


  private

    def user_params
        params.require(:user).permit(:name, :email, :password, :photo, :photo_file_name, :major,
                                     :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
	
	# Returns the Gravatar (http://gravatar.com/) for the given user
	def gravatar_for(user, options = { size: 50 } )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/users/_connect.html.erb
<%= form_for(current_user.connections.build(followed_id: @user.id),
									remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Connect", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_connect_form.html.erb
<% unless current_user?(@user) %>
  <div id="connect_form">
  	<% if current_user.following?(@user) %>
    <%= render 'disconnect' %>
  <% else %>
    <%= render 'connect' %>
  <% end %>


  </div>
<% end %>

app/views/users/_disconnect.html.erb
<%= form_for(current_user.connections.find_by(followed_id: @user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Disconnect", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= image_tag user.photo.url(:thumb) %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete,
								data: { confirm: "Are you sure you want to delete this user" } %>
	<% end %>

</li>

app/views/users/_user_info.html.erb
<div class="user-info-box">
	<table width="100%" cellpadding="0" cellspacing="10" border="0">
	    <tr>
	      <td width="49%" valign="top">
					<h4>Major
						<span class="edit-info">
							<% if current_user?(@user) %>
								<% if @user.major.blank? %>
									<%= link_to " | Declare your major", edit_user_path %>
								<% else %>
									<%= link_to " | Change your major", edit_user_path %>
								<% end %>
							<% end %>
						</span>
					</h4>
					<% if @user.major.blank? %>
						<span class="include-tabs">	Undeclared</span>
					<% else %>
						<span class="include-tabs">	<%=	@user.major %></span>
					<% end %>
	      </td>
	      <td width="2%">
	      </td>
        <td width="49%" valign="top">
          <h4>Skills
          	<span class="edit-info">
		          <% if current_user?(@user) %>
		          	<%= link_to " | List your skills", skills_user_path %>
		          <% end %>
		         </span>
		      </h4>
          <% if @user.skills.any? %>
          	<ul id="skills">
          		<% @user.skills.each do |s| %>
          			<li class="include-tabs" style="list-style-type: none;"> <%=	s.skill %></li>
          		<% end %>
          	</ul>
          <% else %>
          	<span class="include-tabs">	No skills to display</span>
          <% end %>
        </td>
	    </tr>
	    <tr>
	    	<td>
	    		<h4>Interests & Extracurriculars
          	<span class="edit-info">
		          <% if current_user?(@user) %>
		          	<%= link_to " | List your interests", '#' %>
		          <% end %>
		         </span>
		      </h4>
          
	    	</td>
	    	<td></td>
	    	<td>
	    		<h4>Experience
          	<span class="edit-info">
		          <% if current_user?(@user) %>
		          	<%= link_to " | List your experiences", '#' %>
		          <% end %>
		         </span>
		      </h4>
          <% if @user.experiences.any? %>
          	<ul id="skills">
          		<% @user.experiences.each do |s| %>
          			<li class="include-tabs" style="list-style-type: none;"> <%=	s.experience %></li>
          		<% end %>
          	</ul>
          <% else %>
          	<span class="include-tabs">	No experiences to display</span>
          <% end %>
	    	</td>
	    </tr>

	</table>
</div>

app/views/users/add_skill.html.erb
<% provide(:title, "Add skill") %>
<h1>Add Skill</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@new_skill) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :skill, "New skill" %>
      <%= f.text_field :skill %>

      <%= f.submit "Add skill", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit #{@user.name}") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :major %>
      <%= f.text_field :major %>

      <%= f.label :photo, "Profile photo" %>
      <%= f.file_field :photo %>

      <%= f.label :password, "New Password" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm new password" %>
      <%= f.password_field :password_confirmation %>


      
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

	<h1>All users</h1>

	<%= will_paginate %>

	<ul class="users">
		<%= render @users %>
		
	</ul>

	<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for @user, :url => users_path, 
							:html => { :multipart => true } do |f| %>

			<%= render 'shared/error_messages', object: f.object %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :photo, "Profile photo" %>
			<%= f.file_field :photo %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm your password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/old_show.html.erb
<%provide(:title, @user.name) %>
<h1 class="title">
	<% unless current_user?(@user) %>
		<table width="100%">
			<tr>
				<td>
					<%= @user.name %> 
				</td>
				<td>
					<div class="span2">
					    <%= render 'connect_form' if signed_in? %>
					</div>
				</td>
			</tr>
		</table>
	<% else %>
		<%= @user.name %>
	<% end %>

</h1>

<div class="row">
	
	<div class="about-user">
		<div class="profile-box">
			<aside class="span4">
				<div class="profile-photo">
					<%= image_tag @user.photo.url(:medium) %>
				</div>
				<div class="profile-description">
					<strong>Email:</strong> 
					<a href="mailto: <%= @user.email %>"><%= @user.email %></a><br/>
					<% if @user.major.blank? && current_user?(@user) %>
						<%= link_to "Declare your major", edit_user_path(@user) %>
					<% elsif !@user.major.blank? %>
						<strong>Major: </strong><%= @user.major %>
					<% end %>
				</div>
			</aside>
		</div>
	</div>
	<div class="company-container span5">
		<% if @user.companies.any? %>
			<h3 style="display: inline">
				Companies </h3>
			<% if current_user?(@user) %>
				<h2  style="display: inline">
					| <%= link_to "Create a new company", '/companies/new' %>
				</h2>
			<% end %>

			<%= render @companies %>
			<div class="pagination-bottom">
				<%= will_paginate @companies %>
			</div>
		<% elsif current_user?(@user) %>
			<h2>
				<%= link_to "Create your first company!", '/companies/new'%>
			</h2>
		<% else %>
			<h2>No companies to display</h2>
		<% end %>
		
	</div>
</div>
		

app/views/users/show.html.erb
<%provide(:title, @user.name) %>

<div class="user-profile-box">
	<div id="user-photo">
		<%= image_tag @user.photo.url(:medium), class: "user-photo" %>
	</div>

	<h1 class="title">
		<% unless current_user?(@user) %>
			<table width="auto">
				<tr>
					<td>
						<%= @user.name %> 
					</td>
					<td>
						<div class="span2">
						    <%= render 'connect_form' if signed_in? %>
						</div>
					</td>
				</tr>
			</table>
		<% else %>
			<%= @user.name %>
		<% end %>

	</h1>

	<%= render 'user_info' %>

</div>

<div id="company-container" class="company-container">
	<% if @user.memberships.any? %>
		<div class="company-container-header">
			<h3 style="display: inline">
				Companies </h3>
			<% if current_user?(@user) %>
				<h2  style="display: inline">
					| <%= link_to "Create a new company", '/companies/new' %>
				</h2>
			<% end %>
		</div>

		<%= 
			render @companies 
		%>

		<div class="pagination-bottom">
			<%= will_paginate @companies %>
		</div>

	<% elsif current_user?(@user) %>
		<h2>
			<%= link_to "Create your first company!", '/companies/new'%>
		</h2>
	<% else %>
		<h2>No companies to display</h2>
	<% end %>		
</div>






<!-- OLD CODE -->

app/views/users/show_companies.html.erb
<% provide(:title, "My Companies") %>
<h1 style="text-align: left">My Companies</h1>
<%= render @companies %>


<% if false %>
	<% if @companies.any? %>
		<ul class="company-list">
			<% @companies.each do |company| %>
				<li>
					<h2><%= company.title %></h2>
					<%= render partial: 'companies/join_company_form', locals: { company: company} %>
					<br/>
					<h4>Mission </h4>
						<% if company.mission.blank? %>
							This company does not have a mission statement
						<% else %>
							<%= company.mission %>
						<% end %>
				</li>

			<% end %>
		</ul>
	<% end %>
<% end %>

app/views/users/show_connect.html.erb
<% provide(:title, @title) %>
<div class="row">
  

  <!-- <aside class="span4">
    <section>
      <%= link_to image_tag(@user.photo.url(:medium)), @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
    </section>
    <section>

      <% if false %>
       <%= render 'shared/stats' %>
      <% end %>

      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to image_tag(user.photo.url(:tiny)), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside> -->


  <div class="span8">
    <% if @users.any? %>
      <h3><%= @title %></h3>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% else %>
      <h3>No connections to display</h3>
    <% end %>
  </div>
</div>