config/routes.rb
UmichStartups::Application.routes.draw do

  get "connections/create"
  get "connections/destroy"

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users do
    member do
      get :following, :followers, :memberships, :experiences, :skills
    end
  end
  resources :sessions
  resources :companies
  resources :connections
  resources :memberships
  resources :skills

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: :get
  match '/about', to: 'static_pages#about', via: :get
  match '/contact', to:'static_pages#contact', via: :get

  match '/signup', to: 'users#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  	# attr_accessible :title, :user_id, :description, :mission
	belongs_to :user # REMOVE THIS
	validates :title, presence: true

	has_many :memberships, dependent: :destroy

	def team
		team_ids = self.memberships.collect(&:user_id)
		return User.find(team_ids)
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	def create
		# @company = current_user.companies.build(params[:company])
		@company = current_user.companies.build(company_params)
		@company.title = @company.title.titleize
		
		if @company.save && current_user.join_company!(@company)
			flash[:success] = "Company created"
			redirect_to current_user
		else
			render 'new'
		end
	end

	def new
		@company = current_user.companies.build(params[:company])
	end

	def destroy
		#should automatically destroy memberships
		company = Company.find(params[:id])
		company.destroy
		flash[:success] = "#{company.title} has been deleted"
		redirect_to current_user
	end

	def edit 
		@company = Company.find(params[:id])
	end

	def update
		company = Company.find(params[:id])
		if company.update_attributes(company_params)
			unless current_user.member?(company)
				current_user.join_company!(company)
			end
	        flash[:success] = "Company updated"
	        redirect_to current_user
	    else
	        render 'edit'
	    end
	end

	private
		def company_params
			params.require(:company).permit(:title, :user_id, :creator, :description, :mission)
		end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div class="single-company">
	<div class="company-header company-list">
		<table style="min-width: 90%">
			<tr>
				<td>
					<h1 class="company-title">
						"<%= company.title	%>"
					</h1>
				</td>
				<td>
					<%= render partial: '/companies/join_company_form', locals: { company: company } %>					
				</td>
				<% if current_user?(@user) || current_user.admin? %>
					<td>
						<%= link_to "edit", edit_company_path(company) %> |
						<%= link_to "delete", company, method: :delete,
										data: { confirm: "Are you sure you want to delete \"#{company.title}\"" } %>

					</td>
				<% end %>
			</tr>
		</table>

	</div>
		
	<table width="100%">
		<tr>
			<td style="width: 49%">
				<div class="company-about">
					<section>
						<% if company.mission && !company.mission.blank? %>
							<h4 class="company-mission">Mission Statement</h4> 
							<%= company.mission %>
						<% elsif current_user?(@user) %>
							<%= link_to "Add a mission statement for \"#{company.title}\"",
										edit_company_path(company) %>
						<% elsif current_user.admin? %>
							<%= link_to "Edit this company as admin", 
										edit_company_path(company) %>
						<% end %>
					</section>

					<section>
						<% if !company.description.blank? %>
							<h4 class="company-description">Description </h4> 
							<%= company.description %>
						<% elsif current_user?(@user) %>
							<%= link_to "Add a description for \"#{company.title}\"", 
										edit_company_path(company) %>
						<% elsif current_user.admin? %>
							<%= link_to "Edit this company as admin", 
										edit_company_path(company) %>
						<% end %>
					</div>
				</div>
			</td>
			<td style="width: 2%"></td>
			<td width="49%">
				<h4>Team</h4>
				<ul class="team">
					<% team = company.team %>
					
					<% team.each do |t| %>
						<li>
							<%= image_tag t.photo(:thumb), class: "team-member-photo" %>
							<h5><%= t.name %></h5>
						</li>
					<% end %>
				</ul>
			</td>
		</tr>
	</table>

</div>

app/views/companies/_join_company.html.erb
<%= form_for(current_user.memberships.build(company_id: company.id)) do |f| %>
  <div><%= f.hidden_field :company_id %></div>
  <%= f.submit "Join Company", class: "btn btn-primary" %>
<% end %>

app/views/companies/_join_company_form.html.erb
<div class="join-company-form">
	<% if current_user.member?(company) %>
		<%= render partial: 'companies/leave_company', locals: {company: company } %>
	<% else %>
		<%= render partial: 'companies/join_company', locals: { company: company } %>
	<% end %>
</div>

app/views/companies/_leave_company.html.erb
<% if company.memberships.count == 1 %>
	<%= form_for(current_user.memberships.find_by(company_id: company),
	             html: { method: :delete },
	             remote: false,
	             data: { confirm: "Are you sure you want to leave \"#{company.title}.\" \nYou are the last member of this company, if you leave it will be destroyed."},
	             class: 'edit-membership') do |f| %>
	    <%= f.submit "Leave company", class: "btn" %>
	<% end %>
<% else %>
	<%= form_for(current_user.memberships.find_by(company_id: company),
	             html: { method: :delete },
	             remote: false,
	             data: { confirm: "Are you sure you want to leave \"#{company.title}\""},
	             class: 'edit-membership') do |f| %>
	  <%= f.submit "Leave company", class: "btn" %>
	<% end %>

<% end %>

app/views/companies/edit.html.erb
<% provide(:title, "Edit #{@company.title}") %>
<h1>Update <%= @company.title %></h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@company) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.label :mission, "Mission statement" %>
			<%= f.text_area :mission, class: "small-textarea" %>

			<%= f.label :description %>
			<%= f.text_area :description, class: "medium-textarea" %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

		<% end %>
	</div>
</div>

app/views/companies/new.html.erb
<% provide(:title, "New Company") %>
<h1>Create new company</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@company) do |f| %>
			<%= f.label :title %>
			<%= f.text_field :title %>

			<%= f.submit "Create", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>