config/routes.rb
UmichStartups::Application.routes.draw do

  get "connections/create"
  get "connections/destroy"

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users do
    member do
      get :following, :followers, :memberships, :experiences, :skills
    end
  end
  resources :sessions
  resources :companies
  resources :connections
  resources :memberships
  resources :skills

  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: :get
  match '/about', to: 'static_pages#about', via: :get
  match '/contact', to:'static_pages#contact', via: :get

  match '/signup', to: 'users#new', via: :get
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="nav-container">
    <small>
      <%= link_to "UMich Startups", root_url %>
        | Copyright 2013 - Aaron Podell
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <!-- <li><a href="http://news.railstutorial.org/">News</a></li> -->
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <!-- <div class="banner" style="width: 100%; background-color: blue; position: absolute; top: 0" >
    <%= link_to image_tag("banner_logo.png", style: "height: 100px;", class: "offset3"), root_path, id: "logo" %>
  </div> -->
  <!-- <div /*class="navbar-inner affix-top" data-spy="affix" data-offset-top="100px"*/ style="position: relative"> -->
    <div class="nav-container">
      <%= link_to "UMich Startups", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">

          <li><%= link_to "Home", root_path %></li>

          <li><%= link_to "Help", help_path %></li>

          <% if signed_in? %>
            <li id="users-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Users <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All users", users_path %></li>
                <li><%= link_to "Connections", following_user_path(current_user) %></li>
              </ul>
            </li>

            <li id="companies-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Companies <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All companies", '#' %></li>
                <li><%= link_to "My companies", memberships_user_path(current_user) %></li>
              </ul>
            </li>


            <li id="account-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    <!-- </div> -->
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", 
                               "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="globalContainer">
      <div id="buffer-space" style="height: 65px"></div>
      <% flash.each do |key, value| %>
         <div class = "alert alert-<%= key %>"> <%= value %></div>
      <% end %>
      
      <%= yield %>
      <!-- <div style="height: 50px"></div> -->
      <div style="height: 130px"><%= debug(params) if Rails.env.development? %></div>
      <div class="push"></div>
    </div>
    <%= render 'layouts/footer' %>
  
  </body>
</html>